export const COMPANY_INFO = {
  name: 'T47 PEST CONTROL',
  tagline: '24/7 ROUND THE CLOCK',
  phone: '+61 434300216',
  email: 't47pestcontrol@gmail.com',
  social: {
    facebook: 'https://facebook.com/t47pestcontrol',
    instagram: 'https://instagram.com/t47pestcontrol',
    linkedin: 'https://linkedin.com/company/t47pestcontrol',
    twitter: 'https://twitter.com/t47pestcontrol',
    youtube: 'https://youtube.com/c/t47pestcontrol'
  }
};

export const NAVIGATION_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '/services' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
];

export const DROPDOWN_MENU_ITEMS = {
  residential: [
    { name: 'Pest Inspections', href: '/residential/pest-inspections' },
    { name: 'Termite Inspections', href: '/residential/termite-inspections' },
    { name: 'Wasps', href: '/residential/wasps' },
    { name: 'Cockroaches', href: '/residential/cockroaches' },
    { name: 'Mice & Rats', href: '/residential/rats-mice' },
    { name: 'Rodents', href: '/residential/rodents' },
    { name: 'Spiders', href: '/residential/spiders' },
    { name: 'Possums', href: '/residential/possums' },
    { name: 'Ants', href: '/residential/ants' },
    { name: 'Bed Bugs', href: '/residential/bed-bugs' },
    { name: 'Fleas', href: '/residential/fleas' },
    { name: 'Mosquitoes', href: '/residential/mosquitoes' },
    { name: 'Flies', href: '/residential/flies' },
    { name: 'Moths', href: '/residential/moths' },
    { name: 'Silverfish', href: '/residential/silverfish' },
    { name: 'Bird Control', href: '/residential/bird-control' },
    { name: 'Bees', href: '/residential/bees' },
    { name: 'Termites', href: '/residential/termites' },
  ],
  commercial: [
    { name: 'Restaurants', href: '/commercial/restaurants' },
    { name: 'Schools', href: '/commercial/schools' },
    { name: 'Hospitals', href: '/commercial/hospitals' },
    { name: 'Child care', href: '/commercial/childcare' },
    { name: 'Food processing', href: '/commercial/food-processing' },
    { name: 'Retail', href: '/commercial/retail' },
    { name: 'Hotels', href: '/commercial/hotels' },
    { name: 'Offices', href: '/commercial/offices' },
    { name: 'Warehouses', href: '/commercial/warehouses' },
    { name: 'IT Centers', href: '/commercial/it-centers' },
    { name: 'Residential', href: '/commercial/residential' },
    { name: 'Elderly Care Homes', href: '/commercial/elderly-care' },
    { name: 'Gym & Fitness', href: '/commercial/gym-fitness' },
    { name: 'Construction Sites', href: '/commercial/construction-sites' },
  ],
  termite: [
    { name: 'Termite Inspection', href: '/termite-solutions/inspection' },
    { name: 'Termite Treatment', href: '/termite-solutions/treatment' },
    { name: 'Termite Prevention', href: '/termite-solutions/prevention' },
    { name: 'Termite Damage Repair', href: '/termite-solutions/damage-repair' },
    { name: 'Pre-Purchase Inspection', href: '/termite-solutions/pre-purchase' },
    { name: 'Annual Inspection', href: '/termite-solutions/annual' },
    { name: 'Termite Barriers', href: '/termite-solutions/barriers' },
    { name: 'Termite Baiting', href: '/termite-solutions/baiting' },
    { name: 'Termite Monitoring', href: '/termite-solutions/monitoring' },
    { name: 'Commercial Termite', href: '/termite-solutions/commercial' },
  ],
  about: [
    { name: 'About', href: '/about' },
    { name: 'Service Locations', href: '/areas' },
    { name: 'FAQ', href: '/faq' },
  ],
  areas: [
    { name: 'Sydney', href: '/areas/sydney' },
    { name: 'Melbourne', href: '/areas/melbourne' },
    { name: 'Brisbane', href: '/areas/brisbane' },
    { name: 'Perth', href: '/areas/perth' },
    { name: 'Adelaide', href: '/areas/adelaide' },
    { name: 'Gold Coast', href: '/areas/gold-coast' },
    { name: 'Newcastle', href: '/areas/newcastle' },
    { name: 'Canberra', href: '/areas/canberra' },
    { name: 'Wollongong', href: '/areas/wollongong' },
    { name: 'Hobart', href: '/areas/hobart' },
    { name: 'Geelong', href: '/areas/geelong' },
    { name: 'Townsville', href: '/areas/townsville' },
    { name: 'Cairns', href: '/areas/cairns' },
    { name: 'Darwin', href: '/areas/darwin' },
    { name: 'Toowoomba', href: '/areas/toowoomba' },
  ],
};