export const COMPANY_INFO = {
  name: 'T47 PEST CONTROL',
  tagline: '24/7 ROUND THE CLOCK',
  phone: '+61 434300216',
  email: 't47pestcontrol@gmail.com',
  social: {
    facebook: 'https://facebook.com/t47pestcontrol',
    instagram: 'https://instagram.com/t47pestcontrol',
    linkedin: 'https://linkedin.com/company/t47pestcontrol',
    twitter: 'https://twitter.com/t47pestcontrol',
    youtube: 'https://youtube.com/c/t47pestcontrol'
  }
};

export const NAVIGATION_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '/services' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
];

export const DROPDOWN_MENU_ITEMS = {
  residential: [
    { name: 'Pest Inspections', href: '/residential/pest-inspections' },
    { name: 'Termite Inspections', href: '/residential/termite-inspections' },
    { name: 'Wasps', href: '/residential/wasps' },
    { name: 'Rats', href: '/residential/rats' },
    { name: 'Bees', href: '/residential/bees' },
    { name: 'Bed Bugs', href: '/residential/bed-bugs' },
    { name: 'Cockroaches', href: '/residential/cockroaches' },
    { name: 'Flea', href: '/residential/flea' },
    { name: 'Rodents', href: '/residential/rodents' },
    { name: 'Spiders', href: '/residential/spiders' },
    { name: 'Termites', href: '/residential/termites' },
    { name: 'Ants', href: '/residential/ants' },
    { name: 'Mice', href: '/residential/mice' },
    { name: 'Flies', href: '/residential/flies' },
    { name: 'Possum', href: '/residential/possum' },
    { name: 'Silverfish', href: '/residential/silverfish' },
  ],
  commercial: [
    { name: 'All business sectors', href: '/commercial/all' },
    { name: 'Food processing', href: '/commercial/food-processing' },
    { name: 'Logistics & warehousing', href: '/commercial/logistics' },
    { name: 'Hotels', href: '/commercial/hotels' },
    { name: 'Food retail', href: '/commercial/food-retail' },
    { name: 'Pharmaceutical', href: '/commercial/pharmaceutical' },
    { name: 'Offices', href: '/commercial/offices' },
    { name: 'Healthcare', href: '/commercial/healthcare' },
    { name: 'Restaurants', href: '/commercial/restaurants' },
    { name: 'Retail', href: '/commercial/retail' },
  ],
  termite: [
    { name: 'Termite Inspection', href: '/termite-solutions/inspection' },
    { name: 'Termite Treatment', href: '/termite-solutions/treatment' },
    { name: 'Termite Prevention', href: '/termite-solutions/prevention' },
    { name: 'Termite Damage Repair', href: '/termite-solutions/damage-repair' },
    { name: 'Pre-Purchase Inspection', href: '/termite-solutions/pre-purchase' },
    { name: 'Annual Inspection', href: '/termite-solutions/annual' },
    { name: 'Termite Barriers', href: '/termite-solutions/barriers' },
    { name: 'Termite Baiting', href: '/termite-solutions/baiting' },
    { name: 'Termite Monitoring', href: '/termite-solutions/monitoring' },
    { name: 'Commercial Termite', href: '/termite-solutions/commercial' },
  ],
  about: [
    { name: 'Our Team', href: '/about/team' },
    { name: 'Our History', href: '/about/history' },
    { name: 'Testimonials', href: '/about/testimonials' },
    { name: 'Our Mission', href: '/about/mission' },
    { name: 'Our Values', href: '/about/values' },
    { name: 'Careers', href: '/about/careers' },
    { name: 'Awards', href: '/about/awards' },
    { name: 'Certifications', href: '/about/certifications' },
    { name: 'Community', href: '/about/community' },
    { name: 'Partners', href: '/about/partners' },
  ],
  areas: [
    { name: 'Sydney', href: '/areas/sydney' },
    { name: 'Melbourne', href: '/areas/melbourne' },
    { name: 'Brisbane', href: '/areas/brisbane' },
    { name: 'Perth', href: '/areas/perth' },
    { name: 'Adelaide', href: '/areas/adelaide' },
    { name: 'Gold Coast', href: '/areas/gold-coast' },
    { name: 'Newcastle', href: '/areas/newcastle' },
    { name: 'Canberra', href: '/areas/canberra' },
    { name: 'Wollongong', href: '/areas/wollongong' },
    { name: 'Hobart', href: '/areas/hobart' },
    { name: 'Geelong', href: '/areas/geelong' },
    { name: 'Townsville', href: '/areas/townsville' },
    { name: 'Cairns', href: '/areas/cairns' },
    { name: 'Darwin', href: '/areas/darwin' },
    { name: 'Toowoomba', href: '/areas/toowoomba' },
  ],
};