export const COMPANY_INFO = {
  name: 'T47 PEST CONTROL',
  tagline: '24/7 ROUND THE CLOCK',
  phone: '+61 434300216',
  email: 'contact@t47pestcontrol.com.au',
  social: {
    facebook: 'https://facebook.com/t47pestcontrol',
    instagram: 'https://instagram.com/t47pestcontrol',
    linkedin: 'https://linkedin.com/company/t47pestcontrol',
    twitter: 'https://twitter.com/t47pestcontrol',
    youtube: 'https://youtube.com/c/t47pestcontrol'
  }
};

export const NAVIGATION_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '/services' },
  { name: 'About', href: '/about' },
  { name: 'Contact', href: '/contact' },
];

export const DROPDOWN_MENU_ITEMS = {
  residential: [
    { name: 'Pest Inspections', href: '/residential/pest-inspections' },
    { name: 'Termite Inspections', href: '/residential/termite-inspections' },
    { name: 'Wasps', href: '/residential/wasps' },
    { name: 'Cockroaches', href: '/residential/cockroaches' },
    { name: 'Mice & Rats', href: '/residential/rats-mice' },
    { name: 'Rodents', href: '/residential/rodents' },
    { name: 'Spiders', href: '/residential/spiders' },
    { name: 'Possums', href: '/residential/possums' },
    { name: 'Ants', href: '/residential/ants' },
    { name: 'Bed Bugs', href: '/residential/bed-bugs' },
    { name: 'Fleas', href: '/residential/fleas' },
    { name: 'Mosquitoes', href: '/residential/mosquitoes' },
    { name: 'Flies', href: '/residential/flies' },
    { name: 'Moths', href: '/residential/moths' },
    { name: 'Silverfish', href: '/residential/silverfish' },
    { name: 'Bird Control', href: '/residential/bird-control' },
    { name: 'Bees', href: '/residential/bees' },
    { name: 'Termites', href: '/residential/termites' },
  ],
  commercial: [
    { name: 'Restaurants', href: '/commercial/restaurants' },
    { name: 'Schools', href: '/commercial/schools' },
    { name: 'Hospitals', href: '/commercial/hospitals' },
    { name: 'Child care', href: '/commercial/childcare' },
    { name: 'Food processing', href: '/commercial/food-processing' },
    { name: 'Retail', href: '/commercial/retail' },
    { name: 'Hotels', href: '/commercial/hotels' },
    { name: 'Offices', href: '/commercial/offices' },
    { name: 'Warehouses', href: '/commercial/warehouses' },
    { name: 'IT Centers', href: '/commercial/it-centers' },
    { name: 'Residential', href: '/commercial/residential' },
    { name: 'Elderly Care Homes', href: '/commercial/elderly-care' },
    { name: 'Gym & Fitness', href: '/commercial/gym-fitness' },
    { name: 'Construction Sites', href: '/commercial/construction-sites' },
  ],
  termite: [
    { name: 'Termite Inspection', href: '/termite-solutions/inspection' },
    { name: 'Termite Prevention', href: '/termite-solutions/prevention' },
    { name: 'Termite Treatment', href: '/termite-solutions/damage-repair' },
    { name: 'Termite Monitoring', href: '/termite-solutions/monitoring' },
    { name: 'Termite Dusting', href: '/termite-solutions/dusting' },
    { name: 'Termite Foaming', href: '/termite-solutions/foaming' },
    { name: 'Soil Treatment', href: '/termite-solutions/soil-treatment' },
    { name: 'Termite Baiting', href: '/termite-solutions/baiting' },
    { name: 'Nest Elimination', href: '/termite-solutions/nest-elimination' },
    { name: 'Pre-Purchase Inspection', href: '/termite-solutions/pre-purchase' },
    { name: 'Annual Inspection', href: '/termite-solutions/annual' },
    { name: 'Termites for Homes', href: '/termite-solutions/homes' },
    { name: 'Termites for Business', href: '/termite-solutions/business' },
  ],
  about: [
    { name: 'About', href: '/about' },
    { name: 'Local Branches', href: '/local-branches' },
    { name: 'FAQ', href: '/faq' },
  ],
  areas: [
    { name: 'Adelaide', href: '/local-branches/adelaide' },
    { name: 'Albury', href: '/local-branches/albury' },
    { name: 'Ballarat', href: '/local-branches/ballarat' },
    { name: 'Bendigo', href: '/local-branches/bendigo' },
    { name: 'Brisbane', href: '/local-branches/brisbane' },
    { name: 'Cairns', href: '/local-branches/cairns' },
    { name: 'Canberra', href: '/local-branches/canberra' },
    { name: 'Darling Downs', href: '/local-branches/darling-downs' },
    { name: 'Darwin', href: '/local-branches/darwin' },
    { name: 'Geelong', href: '/local-branches/geelong' },
    { name: 'Hobart', href: '/local-branches/hobart' },
    { name: 'Mackay', href: '/local-branches/mackay' },
    { name: 'Melbourne', href: '/local-branches/melbourne' },
    { name: 'Mildura', href: '/local-branches/mildura' },
    { name: 'Newcastle', href: '/local-branches/newcastle' },
    { name: 'Perth', href: '/local-branches/perth' },
    { name: 'Rockhampton', href: '/local-branches/rockhampton' },
    { name: 'Shepparton', href: '/local-branches/shepparton' },
    { name: 'Sydney', href: '/local-branches/sydney' },
    { name: 'Townsville', href: '/local-branches/townsville' },
    { name: 'Victoria', href: '/local-branches/victoria' },
    { name: 'Warrnambool', href: '/local-branches/warrnambool' },
  ],
};